print("welcome to atmiya university")
x=int(20)
print(x)
x=float(20.5)
print(x)
x=complex(1j)
print(x)
x=list["banana","apple","cherry"]
print(x)
x=tuple("apple","banana","cherry")
print(x)
x=range(6)
